# Generated by Django 6.0.4 on 2026-04-24 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='images/no-image.png', null=True, upload_to='products/%Y/%m/%d/', verbose_name='Изображение товара'),
        ),
    ]
