# Generated by Django 6.0.4 on 2026-04-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='images/no-image.png', upload_to='products/%Y/%m/%d/', verbose_name='Изображение товара'),
        ),
    ]
